<?php
# This file was automatically generated by the MediaWiki 1.43.6
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Linqstars Wiki";
$wgMetaNamespace = "Linqstars";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://wiki.linqstars.com";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
    '1x' => "$wgResourceBasePath/resources/assets/Linqstars-Logo.png",
    'icon' => "$wgResourceBasePath/resources/assets/Linqstars-Logo.png",
];

$wgFavicon = "$wgResourceBasePath/resources/assets/Perabo-icon.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "wiki@example.com";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "YOUR_DATABASE_NAME";
$wgDBuser = "YOUR_DATABASE_USER";
$wgDBpassword = "YOUR_DATABASE_PASSWORD";

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "Europe/Amsterdam";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "GENERATE_A_RANDOM_SECRET_KEY";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "GENERATE_A_RANDOM_UPGRADE_KEY";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

# End of automatically generated settings.
# Add more configuration options below.

wfLoadSkin( 'Vector' );
$wgDefaultSkin = 'vector';

# Disable reading by anonymous users
$wgGroupPermissions['*']['read'] = false;

# Disable anonymous editing
$wgGroupPermissions['*']['edit'] = false;

$wgGroupPermissions['*']['autocreateaccount'] = true;

wfLoadExtension( 'GoogleLogin' );

$wgAuthManagerConfig = [
    'primaryauth' => [
        GoogleLogin\Auth\GooglePrimaryAuthenticationProvider::class => [
            'class' => GoogleLogin\Auth\GooglePrimaryAuthenticationProvider::class,
            'sort' => 0
        ]
    ],
    'preauth' => [],
    'secondaryauth' => []
];

$wgInvalidUsernameCharacters = ':~';
$wgUserrightsInterwikiDelimiter = '~';

$wgGLAuthoritativeMode = true;

$wgGLAppId = "YOUR_GOOGLE_OAUTH_CLIENT_ID";
$wgGLSecret = "YOUR_GOOGLE_OAUTH_CLIENT_SECRET";

$wgGLAllowedDomains = [
    'perabo.nl',
    'linqstars.com',
    'proqem.com'
];
$wgGroupPermissions['sysop']['managegooglelogindomains'] = true;

$wgShowExceptionDetails = false;

$wgWhitelistRead = [ 'Special:GoogleLoginReturn','Special:GoogleLoginAllowedDomains' ];

# Enable VisualEditor
wfLoadExtension( 'VisualEditor' );

# Enable wiki source editor toolbar
wfLoadExtension( 'WikiEditor' );

# Show separate tabs (Create + Create source / Edit + Edit source)
$wgVisualEditorUseSingleEditTab = false;

# Allow switching to source mode
$wgVisualEditorEnableWikitext = true;

# Turn on VE by default for users
$wgDefaultUserOptions['visualeditor-enable'] = 1;

# Turn on source editor toolbar by default for users
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;
$wgDefaultUserOptions['wikieditor-publish'] = 1;

# Make sure logged-in users can create pages
$wgGroupPermissions['user']['createpage'] = true;
$wgGroupPermissions['user']['edit'] = true;
$wgGroupPermissions['user']['read'] = true;

# Drawio + BlueSpice dependencies
wfLoadExtension( 'BlueSpiceFoundation' );
#wfLoadExtension( 'ExtJSBase' );
wfLoadExtension( 'OOJSPlus' );
wfLoadExtension( 'DrawioEditor' );

# Drawio options
$wgDrawioEditorImageInteractive = true;
$wgDrawioEditorImageType = 'svg';

wfLoadExtension( 'PageApprovals' );

wfLoadExtension( 'InputBox' );

wfLoadExtension( 'Widgets' );